name: flutter_auth_social
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.6
  firebase_core: ^0.3.1+1
  firebase_auth: ^0.8.1+4
  flutter_auth_buttons: ^0.3.1

 
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  google_sign_in: ^4.0.1+1



flutter:

 
  uses-material-design: true

  assets:
    - assets/images/

  